---
- hosts: localhost
  sudo: yes  
  tasks:
    - name: Install all dependencies
      yum:
        name: "{{ item }}"
        state: present

      with_items:
        - java-1.8.0-openjdk
        - git
        
    - name: Download jenkins repo
      shell: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo"

    - name: Import Jenkins CI key
      rpm_key:
        key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
        state: present

    - name: Install Jenkins
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - jenkins

    - name: Allow port 8080
      shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

    - name: Start the server
      service:
      name: jenkins
      state: started
