---
- name: Create Nginx Server
  hosts: localhost
  become: false
  connection: local
  gather_facts: false

  vars:
    region: us-east-1
    ami: ami-04681a1dbd79675a5
    instance_type: t2.micro
    security_group: default
    keypair: my-key
    groupname: webserver
#    aws_access_key: AKIAIJBI4UVD62LDAUBA
#    aws_secret_key: 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
    subnet: subnet-86b612da

  tasks:

    - name: Luanch Nginx Server
      ec2:
        region: "{{ region }}"
        image: "{{ ami }}"
        instance_type: "{{ instance_type }}"
        group: "{{ security_group }}"
        key_name: "{{ keypair }}"
        wait: yes
        assign_public_ip: yes
        vpc_subnet_id: "{{ subnet }}"
      register: ec2

    - name: Add new instance to the host group
      add_host: hostname={{ item.public_ip }} groupname={{ groupname }}
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=300 state=started
      with_items: "{{ ec2.instances }}"

- name: Configure new instance
  hosts: webserver
  sudo: yes
  remote_user: ec2-user
  gather_facts: true
- include: nginx-configure.yml

